# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://github.com/q474818917
date_format: "ordinal"
title: Altas 
subtitle: "任何一门学科深入之后都很枯燥"
description: "任何一门学科深入之后都很枯燥"
keywords: Java, golang, vertx, q474818917
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: q474818917
organization: hiyosoft
organization_url: https://github.com/hiyosoft
github_username: q474818917
location: Yangzhou, China
email: q474818917@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: q474818917/q474818917.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
disqus_username: 
netease_gentie_key: 
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 
